  server:
    port: 8080
#mybatis
  mybatis:
    mapper-locations: classpath*:com/hxf/mall/**/mapper/*.xml,classpath*:mapper/*.xml
#mysql
  spring:
    datasource:
      url: jdbc:mysql://192.168.0.187:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: zaURS)3Lv H5AwfZ
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: 45.77.10.18 # Redis服务器地址
        database: 0 # Redis数据库索引（默认为0）
        port: 6379 # Redis服务器连接端口
        password: hxf123456 # Redis服务器连接密码（默认为空）
        jedis:
          pool:
            max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 8 # 连接池中的最大空闲连接
            min-idle: 0 # 连接池中的最小空闲连接
        timeout: 3000ms # 连接超时时间（毫秒）

# 自定义jwt key
  jwt:
    tokenHeader: Authorization #JWT存储的请求头
    secret: mySecret #JWT加解密使用的密钥
    expiration: 604800 #JWT的超期限时间(60*60*24)
    tokenHead: Bearer  #JWT负载中拿到开头
  # 自定义redis key
  redis:
    key:
      prefix:
        authCode: "portal:authCode:"
      expire:
        authCode: 120 # 验证码超期时间

