  server:
    port: 8080
#mybatis
  mybatis:
    mapper-locations:
      classpath*: com/hxf/mall/**/mapper/*.xml
      classpath*: mapper/*.xml
#mysql
  spring:
    datasource:
      url: jdbc:mysql://192.168.0.187:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: zaURS)3Lv H5AwfZ
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头


