  server:
    port: 8080
#mybatis
  mybatis:
    mapper-locations:
      - classpath*:com/hxf/mall/**/mapper/*.xml
#mysql
  spring:
    datasource:
      url: jdbc:mysql://192.168.0.187:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: zaURS)3Lv H5AwfZ
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver

